### ISSUE TITLE
Skipping invalid URL (Error processing) when crawling applicaiton

### ISSUE THREAD

**Issue by astepanova911** [Wopee-io/playwright-ai-bot-demo#11]
Once I have created auth.json file to authenticate against the application following errors during crawling:

npm run crawl

> playwright-ai-bot-demo@1.0.0 crawl
> playwright-ai-bot crawl

Using URL from config: https://xxx.xxxxx.local
Starting crawling the website: https://xxx.xxxxx.local
Saving data to: playbot-data
Limit set to: 10 pages
Skipping invalid URL: 
Skipping invalid URL: 
Skipping invalid URL: 
✘ Error processing https://xxxxxxl.local:446/: page.goto: net::ERR_CONNECTION_REFUSED at https://XXXX.XXXX.local:446/
Call log:
  - navigating to "https://XXXXX.local:446/", waiting until "load"

    at processLinks (C:\Users\XXXX\source\repos\playwright-ai-bot-demo\node_modules\playwright-ai-bot\dist\actions\crawl.js:39:28)
    at async crawl (C:\Users\XXXXX\source\repos\playwright-ai-bot-demo\node_modules\playwright-ai-bot\dist\actions\crawl.js:13:22)
    at async Command.<anonymous> (C:\Users\XXXXX\source\repos\playwright-ai-bot-demo\node_modules\playwright-ai-bot\dist\commands\crawl.js:55:29) {
  name: 'Error'
}
✘ Error processing https://xxxxxxHelp: page.goto: Navigation to "https://xxxxxxx/Help" is interrupted by another navigation to "chrome-error://chromewebdata/"
Call log:
  - navigating to "https://xxxxxx/Help", waiting until "load"

    at processLinks (C:\Users\xxxx\source\repos\playwright-ai-bot-demo\node_modules\playwright-ai-bot\dist\actions\crawl.js:39:28)
    at async crawl (C:\Users\xxxx\source\repos\playwright-ai-bot-demo\node_modules\playwright-ai-bot\dist\actions\crawl.js:13:22)
    at async Command.<anonymous> (C:\Users\xxxxx\source\repos\playwright-ai-bot-demo\node_modules\playwright-ai-bot\dist\commands\crawl.js:55:29) {
  name: 'Error'
}
Skipping invalid URL: 
✘ Error processing : page.title: Execution context was destroyed, most likely because of a navigation
    at processLinks (C:\Users\XXXXXXX\source\repos\playwright-ai-bot-demo\node_modules\playwright-ai-bot\dist\actions\crawl.js:44:39)
    at async crawl (C:\Users\xxxx\source\repos\playwright-ai-bot-demo\node_modules\playwright-ai-bot\dist\actions\crawl.js:13:22)
    at async Command.<anonymous> (C:\Users\xxxx\source\repos\playwright-ai-bot-demo\node_modules\playwright-ai-bot\dist\commands\crawl.js:55:29) {
  name: 'Error'
}
✘ Error processing https://XXXXX.XXXXX.local/Filters: page.goto: Navigation to "https://XXX.XXXXX.local/Filters" is interrupted by another navigation to "https://XXX.XXXX.local/Help"
Call log:
  - navigating to "https://XXXXX.XXXXX.local/Filters", waiting until "load"

    at processLinks (C:\Users\xxxxx\source\repos\playwright-ai-bot-demo\node_modules\playwright-ai-bot\dist\actions\crawl.js:39:28)
    at async crawl (C:\Users\xxxx\source\repos\playwright-ai-bot-demo\node_modules\playwright-ai-bot\dist\actions\crawl.js:13:22)
    at async Command.<anonymous> (C:\Users\xxxxx\source\repos\playwright-ai-bot-demo\node_modules\playwright-ai-bot\dist\commands\crawl.js:55:29) {
  name: 'Error'
}
✔ Crawling completed successfully

Maybe happening because there is popup after login
![image](https://github.com/user-attachments/assets/0d139701-494d-4d3d-bc81-77c4ff91f859)

**Comment by marcel-veselka** [comment]
Thank you for reporting the issue. @astepanova911 

We received several similar reports, so I completely rewrote the crawler. It will now collect data after every interaction (such as clicking, filling out forms, selecting options, etc.) within the crawled application.

Please retest using the latest version (1.12.0).
Please let me know if it works now better.

**Comment by astepanova911** [comment]
The issue from above is not happening any more. Thanks Marcel! I am trying to figure out now how to pass the authentication and test inside the application

**Comment by marcel-veselka** [comment]
@astepanova911 
Here's the link to the documentation on how to set auth up:
https://www.npmjs.com/package/playwright-ai-bot#:~:text=Authentication%20and%20Cookies%20Handling
